apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "docker-registry.fullname" . }}-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{ include "docker-registry.labels" . | nindent 4 }}
data:
  config.yml: |-
{{ toYaml .Values.configData | indent 4 }}
