{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "docker-registry.fullname" . }}-servicemonitor
  labels:
{{ include "docker-registry.labels" . | indent 4 }}
{{- if .Values.metrics.serviceMonitor.labels }}
{{ toYaml .Values.metrics.serviceMonitor.labels | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{ include "docker-registry.match-labels" . | nindent 6 }}
  endpoints:
  - port: http-metrics
    interval: 15s
{{- end }}
